apiVersion: v1
kind: Secret
metadata:
  labels:
    app: hardware-console-exporter
  name: hardware-console-exporter
  namespace: monsoon3
data:
  EXPORTER_DELL_PASSWORD: {{ .Values.consoles.dell.password  | b64enc | quote }}
  EXPORTER_LENOVO_PASSWORD: {{ .Values.consoles.lenovo.password | b64enc | quote }}
  EXPORTER_HPE_PASSWORD: {{ .Values.consoles.hpe.password | b64enc | quote }}
