owner-info:
  support-group: foundation
  service: hwconsole-exporter
  maintainers:
    - Stefan Hipfel
    - Bernd Kuespert
    - Jens Sandmann
  helm-chart-url: https://github.com/sapcc/hardware-console-exporter/tree/main/charts

global:
  linkerd_requested: true

replicaCount: 1

hardware_console_exporter:
  image:
    repository: hardware-console-exporter
    pullPolicy: IfNotPresent
    tag: "latest"

debug:
  enabled: false

consoles:
  dell:
    username: "hw_admin"
    policy_name: "firmware_80u3_01_2025"
    password: DEFINED_IN_SECRET
  hpe:
    username: "hw_admin"
    password: DEFINED_IN_SECRET
  lenovo:
    username: "hw_admin"
    policy_name: "firmware_80u3_03_2025"
    password: DEFINED_IN_SECRET
  # Interval in minutes to run the console exporter.
  interval_in_min: 1440

podAnnotations: {}

podSecurityContext: {}

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Deploy Prometheus alerts.
alerts:
  enabled: true
  # Name of the Prometheus to which the alerts should be assigned to.
  prometheus: infra-collector
  support_group: foundation
